### ISSUE TITLE
centernode is onnodig klikbaar

### ISSUE THREAD

**Issue by robertjuh** [robertjuh/HZ-EMM-3D-Widget#3]
-suggestie van jethro

Als de gebruiker op de node van de huidige pagina klikt wordt deze uitgevoerd. 

Oplossing: er hoeft geen callbackfunctie komen op de center node

**Comment by antonbil** [comment]
Hoi Robert (en Jethro)

Wouter zei dit ook al. Dit is al gefikst. En verder ook gefikst het rekening houden met een overzicht waar geen relaties zijn.

Groeten,

Anton

---

Van: robertjuh notifications@github.com
Verzonden: dinsdag 15 december 2015 12:10
Aan: robertjuh/HZ-EMM-3D-Widget
Onderwerp: [HZ-EMM-3D-Widget] centernode is onnodig klikbaar (#3)

-suggestie van jethro

Als de gebruiker op de node van de huidige pagina klikt wordt deze uitgevoerd

Oplossing: er hoeft geen callbackfunctie komen op de center node

## 

Reply to this email directly or view it on GitHubhttps://github.com/robertjuh/HZ-EMM-3D-Widget/issues/3.

Vlissingen K.v.K.: 41114014
Disclaimer: hz.nl/disclaimerhttp://hz.nl/disclaimer
